name: Run Unit Tests

on: [push]

jobs:
  build:

    runs-on: macos-15

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
